#!/bin/bash
aurGitDir=~/gitapps/AUR
if [ "$1" = --git ]; then
  repo_name=$(basename "$PWD")-git
else
  repo_name=${1:-$(basename "$PWD")}
fi

if [ -d "$aurGitDir/$repo_name" ]; then
  cd "$aurGitDir/$repo_name"
elif [ -d "$aurGitDir/$repo_name-git" ]; then
  cd "$aurGitDir/$repo_name-git"
else
  exit 1
fi

makepkg
makepkg --printsrcinfo > .SRCINFO
rm -rf src pkg "$repo_name"*
git commit -m "update to the latest version" PKGBUILD .SRCINFO
git push
